[package]
name = "permutations"
version = "0.1.0"
authors = ["Julian Fleischer <tirednesscankill@warhog.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
