[package]
name = "factors"
version = "0.1.0"
authors = ["Julian Fleischer <tirednesscankill@warhog.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.20.2"
